import Link from "next/link";
import { Building2, Compass, DraftingCompass, Gem, Globe2, ShieldCheck } from "lucide-react";
import { EnquiryForm } from "@/components/enquiry-form";

const services=[
  {icon:Compass,title:"Scientific Vastu",text:"Evidence-led Vedic principles applied to homes, workplaces and industrial environments."},
  {icon:Building2,title:"Architecture & Structure",text:"Thoughtful planning, structural coordination and execution-ready design solutions."},
  {icon:Gem,title:"Interior & 3D Design",text:"Refined interiors and visualisations that align aesthetics, function and directional harmony."}
];
export default function Home(){return <>
  <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Modern design · timeless wisdom</div><h1>Spaces designed for <em>purpose, harmony & growth.</em></h1><p className="lead">Complete architecture, structural design and scientific Vastu consultancy from CE. SS Attri—serving homes and organisations across India and worldwide.</p><div className="actions"><Link href="/book-consultation" className="btn gold">Talk to an expert</Link><Link href="/projects" className="btn outline">Explore our work</Link></div></div><aside className="metric-card"><div className="eyebrow">One integrated practice</div><h2>Clarity from site selection to final space.</h2><div className="metric-grid"><div className="metric"><strong>360°</strong><span>Design solutions</span></div><div className="metric"><strong>Global</strong><span>Remote consulting</span></div><div className="metric"><strong>Vedic</strong><span>Rooted approach</span></div><div className="metric"><strong>Modern</strong><span>Technical rigour</span></div></div></aside></div></section>
  <section className="section"><div className="container"><div className="section-head"><div className="eyebrow">Our expertise</div><h2>Design intelligence, grounded in direction.</h2><p className="muted">From the first site reading to the final material palette, every decision works toward a space that performs beautifully.</p></div><div className="grid-3">{services.map(({icon:Icon,title,text})=><article className="card" key={title}><div className="icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p><Link href="/services">Discover more →</Link></article>)}</div></div></section>
  <section className="section" style={{background:"#f4eadb"}}><div className="container feature"><div className="mandala" role="img" aria-label="Geometric Vastu-inspired architectural motif"/><div><div className="eyebrow">The Attri approach</div><h2>Ancient principles. Contemporary precision.</h2><p className="muted">We combine directional science, architecture and engineering in one coordinated process—so recommendations are practical, measurable and appropriate for modern life.</p><div className="check"><ShieldCheck/><span><b>Context before correction</b><br/><span className="muted">Recommendations shaped around your site, goals and constraints.</span></span></div><div className="check"><DraftingCompass/><span><b>Design-ready guidance</b><br/><span className="muted">Clear plans your architects, engineers and teams can use.</span></span></div><div className="check"><Globe2/><span><b>Worldwide consultation</b><br/><span className="muted">Secure remote sessions, reports and ongoing collaboration.</span></span></div></div></div></section>
  <section className="section dark"><div className="container feature"><div><div className="eyebrow">Start a conversation</div><h2>Tell us what you are planning.</h2><p className="lead">Share a few details and our team will help you choose the right consultation or design service.</p></div><EnquiryForm/></div></section>
  </>}
